### PR TITLE
Moving SRAM docs from gf180mcu-pdk

### LINKED ISSUE #11: Move the SRAM documentation into the SRAM IP repository
The documentation at https://github.com/google/gf180mcu-pdk/tree/main/docs/digital/SRAM should be in the repository found at https://github.com/google/globalfoundries-pdk-ip-gf180mcu_fd_ip_sram

### PR DESCRIPTION
**Pull request by mohanad0mohamed**
- Moved all documentations in `docs` directory.
- Made symbolic link for it in [gf180mcu-pdk](https://github.com/google/gf180mcu-pdk)

- [x] Built locally with no errors

Fixes https://github.com/google/gf180mcu-pdk/issues/11

### CODE REVIEW

**Comment by mithro** [comment]
I have reworked this pull request slightly. I move the specs to a `specs` directory under each cell. See the commit at https://github.com/google/globalfoundries-pdk-ip-gf180mcu_fd_ip_sram/commit/894afa53abe42b2cad8ce9460dc7b4c0ec43fc44

**Comment by mithro** [comment]
@mohanad0mohamed - I have updated this pull request for you.

**Comment by mohanad0mohamed** [comment]
Thanks @mithro. I was going to do the same but I didn't know that I can put directories inside each cell.
I thought this shouldn't happen so I made them in `docs` directory.

**Comment by mohanad0mohamed** [comment]
I have moved code_of_conduct.rst and contributing.rst outside docs not to produce warnings. Also edited README.rst to change 180um to 180nm.

I think this edit should happen also in [mcu7t5v0](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu7t5v0) and [mcu9t5v0](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0) not to produce warnings in building the docs.

**Comment by mithro** [comment]
> I have moved code_of_conduct.rst and contributing.rst outside docs not to produce warnings. Also edited README.rst to change 180um to 180nm.

Two comments;
 * Please keep pull requests to a single item. 
 * We should fix the warnings from these docs, not remove the docs all together.

**Comment by mithro** [comment]
@mohanad0mohamed - I have removed the non-moving SRAM docs changes from this pull request.

**Pull request merged**
